-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: /var/www/wiki/mediawiki/extensions/GlobalUserrights/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE global_user_groups (
  gug_user BIGINT NOT NULL,
  gug_group TEXT DEFAULT '' NOT NULL,
  gug_expiry TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(gug_user, gug_group)
);

CREATE INDEX gug_group ON global_user_groups (gug_group);

CREATE INDEX gug_expiry ON global_user_groups (gug_expiry);
