-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: /var/www/wiki/mediawiki/extensions/GlobalUserrights/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/global_user_groups (
  gug_user BIGINT UNSIGNED NOT NULL,
  gug_group VARBINARY(255) DEFAULT '' NOT NULL,
  gug_expiry BINARY(14) NOT NULL,
  INDEX gug_group (gug_group),
  INDEX gug_expiry (gug_expiry),
  PRIMARY KEY(gug_user, gug_group)
) /*$wgDBTableOptions*/;
